### ISSUE TITLE
Exim log is not parsed

### ISSUE THREAD

**Issue by drlight17** [dmxengine/EximLogAnalyzer#2]
Just tested version 1.0.20160930 and there is nothing in all tabs? except tab "Not parsed log lines" that contains full exim log file. Exim version 4.86_2 #1 built 10-Feb-2018 19:18:40
It isn't supported is it?

**Comment by dmxengine** [comment]
Hi, can you provide log file from your exim version? Because currently I
don't use your version of exim. Thanks.

вт, 2 апр. 2019 г., 5:06 ПП drlight17 notifications@github.com:

**Comment by drlight17** [comment]
Sure. Here you go
[mainlog.txt](https://github.com/dmxengine/EximLogAnalyzer/files/3037072/mainlog.txt)

**Comment by drlight17** [comment]
However, these logs are perfectly parsing with old exilog (last updated in 2004-2005)

**Comment by dmxengine** [comment]
Hi, sorry for the delay in the response. Please try to set in Exim config log_selector = +all
Hope it's helps. Thanks.

**Comment by drlight17** [comment]
Good day. Yes,  "config log_selector = +all" helped.  My config was:  
log_selector=  \
    -delay_delivery \
    -queue_run \
    -size_reject \
    -skip_delivery
However, what "-" selector cause eximloganalizer not to parse maillog?

**Comment by dmxengine** [comment]
Because log format changes depending on log_selector options. When I develop this software I don't spend time to adapt for parsing with various log_selector options. +all option allows you to see the full picture. Enjoy :)

**Comment by drlight17** [comment]
Ok, i got it. Thanks! ;)
