### ISSUE TITLE
Regex queries need update

### ISSUE THREAD

**Issue by mucke5** [dmxengine/EximLogAnalyzer#6]
@dmxengine can you please check your regex queries? We have already corrected one line to give you an idea of what is being asked for. ⇾ UPDATED vs. CURRENT

```
// https://github.com/dmxengine/EximLogAnalyzer/blob/master/EximLogAnalyzer/LogParser.cs

string logLine
var match = regex.Match(logLine)

UPDATED
137: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (\[(\d+)]) (\w{6}-\w{6}-\w{2}) (Completed|\S\S) (<>)?

CURRENT
137: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) (<=|=>|->|Completed|\*\*|==) (<>)?
213: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) == (.+?) \((.+)\) <(.+?)> R=.+defer \(-?\d{0,3}\):(.+)
241: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) == (.+?) <(.+?)> R=.+defer \(-?\d{0,3}\):(.+)
270: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) == (.+?\s).+T=.+defer \(-?\d{0,3}\):(.+)
301: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) == (.+?\s).+defer \(-?\d{0,3}\):(.+)
340: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) \*\* (.+?)\s.+T=.+?:(.+)
371: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) \*\* (.+?)\s.+?:(.+)
402: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) \*\* (.+?):(.+)
434: (T=""(.*?)"")? from <(.+)?> for (.+)
449: H=(.+?) \[(.+?)\].+\sS=(.+?)\s
458: (T=""(.*?)"")? from <(.+)?> for (.+)
479: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) (=>|->) ([^\s]+)\s<(.+?)> F=<
497: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) (=>|->) (.+?) \((.+)\) <(.+?)> F=
516: (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(\d.+?)] (.{6}-.{6}-.{2}) (=>|->) ([^\s]+) F=<.+C=""(.+?)""
545: QT=(.+?)\sDT=(.+)
557: \\\d{3}\\\d{3}
```

**Comment by dmxengine** [comment]
Good day @mucke5 ! What is the purpose of these changes? What will we get?

**Comment by mucke5** [comment]
Good day @dmxengine ! We have already adjusted our log_selector in /etc/exim4/exim4.conf to
```
log_selector = -retry_defer -skip_delivery -queue_run +pid +received_recipients +sender_on_delivery +delivery_size +incoming_interface +incoming_port +address_rewrite +smtp_confirmation +queue_time +queue_time_overall +smtp_connection +smtp_incomplete_transaction +subject +deliver_time +tls_sni +unknown_in_list
```
This way, we could already achieve that your regex queries are partially filled in some way. Anyway, the CURRENT regex queries give us an error, so we checked and saw that with an UPDATED regex query the data is extracted correctly.

Our system is [Ubuntu 18.04 with exim4 4.90.1-1ubuntu1.8](https://launchpad.net/ubuntu/bionic/+source/exim4).
Thank you for your help and feedback on this matter.

**Comment by dmxengine** [comment]
@mucke5 I would be extremely grateful if you could send me your log file, because I don't have the ability to "generate" logs based on your logging format settings. My email *** Thanks!

**Comment by mucke5** [comment]
@dmxengine I would be very happy if you could take a look at the mail I sent you. 
Password: `EximLogAnalyzer`

Hopefully with this help you can provide me with a customized LogParser.cs where the regex queries fit.
Thanks a lot for your help!

**Comment by mucke5** [comment]
The solution to make it work with exim4.90_1 (or older version):
[Setting log_selector = +all -millisec](https://github.com/Exim/exim/blob/master/doc/doc-txt/ChangeLog)
`JH/39 Fix syslog logging for syslog_timestamp=no and log_selector +millisec.
      Previously the millisecond value corrupted the output.
      Fix also for syslog_pid=no and log_selector +pid, for which the pid
      corrupted the output.`
